services:
  dev:
    image: sibedge/postgres-plv8:16.8-3.2.3
    restart: unless-stopped
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    volumes:
      - dev_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"

  postgresOne:
    image: sibedge/postgres-plv8:16.8-3.2.3
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "10s"

volumes:
  dev_data:
  data:
