import { integer } from "@monorepo/pg/schema/column/data-types/integer.js";
import { schema } from "@monorepo/pg/schema/schema.js";
import { table } from "@monorepo/pg/schema/table.js";
import { sql } from "kysely";
import { test } from "vitest";
import { assertSchemaPush } from "~tests/__setup__/helpers/build-test-case.js";
import {
	columnRename,
	tableRename,
} from "~tests/__setup__/helpers/factories/renames.js";
import type { TestContext } from "~tests/__setup__/setup.js";

test<TestContext>("add identity", async (context) => {
	await assertSchemaPush({
		context,
		before: async (context) => {
			await sql
				.raw(
					`create table "public"."users" ("id" integer, "byDefault" integer);`,
				)
				.execute(context.dbClient);
		},
		schema: schema({
			tables: {
				users: table({
					columns: {
						id: integer().generatedAlwaysAsIdentity(),
						byDefault: integer().generatedByDefaultAsIdentity(),
					},
				}),
			},
		}),
		expectedQueries: [
			'alter table "public"."users" add constraint "temporary_not_null_check_constraint_public_users_byDefault" check ("byDefault" IS NOT NULL) not valid',
			'alter table "public"."users" validate constraint "temporary_not_null_check_constraint_public_users_byDefault"',
			'alter table "public"."users" alter column "byDefault" set not null',
			'alter table "public"."users" drop constraint "temporary_not_null_check_constraint_public_users_byDefault"',
			'alter table "public"."users" add constraint "temporary_not_null_check_constraint_public_users_id" check ("id" IS NOT NULL) not valid',
			'alter table "public"."users" validate constraint "temporary_not_null_check_constraint_public_users_id"',
			'alter table "public"."users" alter column "id" set not null',
			'alter table "public"."users" drop constraint "temporary_not_null_check_constraint_public_users_id"',
			'ALTER TABLE "public"."users" ALTER COLUMN "byDefault" ADD GENERATED BY DEFAULT AS IDENTITY',
			'ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY',
		],
		assertDatabase: async ({ assert, refute }) => {
			await assert.columnWithIdentity("id", "public.users");
			await assert.columnWithIdentity("byDefault", "public.users");
			await refute.columnNullable("id", "public.users");
			await refute.columnNullable("byDefault", "public.users");
		},
	});
});

test<TestContext>("drop identity and drop not null", async (context) => {
	await assertSchemaPush({
		context,
		before: async (context) => {
			await sql
				.raw(
					`create table "public"."users" ("id" integer generated always as identity not null);`,
				)
				.execute(context.dbClient);
		},
		schema: schema({
			tables: {
				users: table({
					columns: {
						id: integer(),
					},
				}),
			},
		}),
		expectedQueries: [
			'ALTER TABLE "public"."users" ALTER COLUMN "id" DROP IDENTITY',
			'alter table "public"."users" alter column "id" drop not null',
		],
		assertDatabase: async ({ assert, refute }) => {
			await refute.columnWithIdentity("id", "public.users");
			await assert.columnNullable("id", "public.users");
		},
	});
});

test<TestContext>("drop identity and maintain not null", async (context) => {
	await assertSchemaPush({
		context,
		before: async (context) => {
			await sql
				.raw(
					`create table "public"."users" ("id" integer generated always as identity not null);`,
				)
				.execute(context.dbClient);
		},
		schema: schema({
			tables: {
				users: table({
					columns: {
						id: integer().notNull(),
					},
				}),
			},
		}),
		expectedQueries: [
			'ALTER TABLE "public"."users" ALTER COLUMN "id" DROP IDENTITY',
		],
		assertDatabase: async ({ refute }) => {
			await refute.columnNullable("id", "public.users");
			await refute.columnWithIdentity("id", "public.users");
		},
	});
});

test<TestContext>("add column itentity to renamed column", async (context) => {
	await assertSchemaPush({
		context,
		before: async (context) => {
			await sql
				.raw(`create table "public"."users" ("id" integer);`)
				.execute(context.dbClient);
		},
		schema: schema({
			tables: {
				users: table({
					columns: {
						id2: integer().generatedAlwaysAsIdentity(),
					},
				}),
			},
		}),
		renames: {
			tables: [],
			columns: {
				"public.users": [columnRename("public", "users", "id", "id2")],
			},
		},
		expectedQueries: [
			'alter table "public"."users" rename column "id" to "id2"',
			'alter table "public"."users" add constraint "temporary_not_null_check_constraint_public_users_id2" check ("id2" IS NOT NULL) not valid',
			'alter table "public"."users" validate constraint "temporary_not_null_check_constraint_public_users_id2"',
			'alter table "public"."users" alter column "id2" set not null',
			'alter table "public"."users" drop constraint "temporary_not_null_check_constraint_public_users_id2"',
			'ALTER TABLE "public"."users" ALTER COLUMN "id2" ADD GENERATED ALWAYS AS IDENTITY',
		],
		assertDatabase: async ({ assert, refute }) => {
			await refute.columnNullable("id2", "public.users");
			await assert.columnWithIdentity("id2", "public.users");
		},
	});
});

test<TestContext>("add column identity to renamed table and column", async (context) => {
	await assertSchemaPush({
		context,
		before: async (context) => {
			await sql
				.raw(`create table "public"."users" ("id" integer);`)
				.execute(context.dbClient);
		},
		schema: schema({
			tables: {
				accounts: table({
					columns: {
						id2: integer().generatedAlwaysAsIdentity(),
					},
				}),
			},
		}),
		renames: {
			tables: [tableRename("public", "users", "accounts")],
			columns: {
				"public.accounts": [columnRename("public", "users", "id", "id2")],
			},
		},
		expectedQueries: [
			'alter table "public"."users" rename to "accounts"',
			'alter table "public"."accounts" rename column "id" to "id2"',
			'alter table "public"."accounts" add constraint "temporary_not_null_check_constraint_public_accounts_id2" check ("id2" IS NOT NULL) not valid',
			'alter table "public"."accounts" validate constraint "temporary_not_null_check_constraint_public_accounts_id2"',
			'alter table "public"."accounts" alter column "id2" set not null',
			'alter table "public"."accounts" drop constraint "temporary_not_null_check_constraint_public_accounts_id2"',
			'ALTER TABLE "public"."accounts" ALTER COLUMN "id2" ADD GENERATED ALWAYS AS IDENTITY',
		],
		assertDatabase: async ({ assert, refute }) => {
			await refute.columnNullable("id2", "public.accounts");
			await assert.columnWithIdentity("id2", "public.accounts");
		},
	});
});
