import { Difference } from "microdiff";
import {
	ChangeSetType,
	Changeset,
	MigrationOpPriority,
} from "~/changeset/types.js";
import type {
	DbTableInfo,
	LocalTableInfo,
} from "~/introspection/introspection.js";
import { executeKyselyDbStatement } from "../../../../../changeset/helpers.js";
import type { ColumnInfo } from "../types.js";

export function columnIdentityMigrationOpGenerator(
	diff: Difference,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	_addedTables: string[],
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	_droppedTables: string[],
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	_local: LocalTableInfo,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	_db: DbTableInfo,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	schemaName: string,
) {
	if (isColumnIdentityAdd(diff)) {
		return columnIdentityAddMigrationOperation(diff, schemaName);
	}
	if (isColumnIdentityDrop(diff)) {
		return columnIdentityDropMigrationOperation(diff, schemaName);
	}
}

type IdentityAddDifference = {
	type: "CHANGE";
	path: ["table", string, "columns", string, "identity"];
	value: NonNullable<ColumnInfo["identity"]>;
	oldValue: null;
};

type IdentityDropDifference = {
	type: "CHANGE";
	path: ["table", string, "columns", string, "identity"];
	value: null;
	oldValue: NonNullable<ColumnInfo["identity"]>;
};

function isColumnIdentityAdd(test: Difference): test is IdentityAddDifference {
	return (
		test.type === "CHANGE" &&
		test.path[0] === "table" &&
		test.path.length === 5 &&
		test.path[2] === "columns" &&
		test.path[4] === "identity" &&
		test.value !== null &&
		test.oldValue === null
	);
}

function isColumnIdentityDrop(
	test: Difference,
): test is IdentityDropDifference {
	return (
		test.type === "CHANGE" &&
		test.path[0] === "table" &&
		test.path.length === 5 &&
		test.path[2] === "columns" &&
		test.path[4] === "identity" &&
		test.value === null &&
		test.oldValue !== null
	);
}

function columnIdentityAddMigrationOperation(
	diff: IdentityAddDifference,
	schemaName: string,
) {
	const tableName = diff.path[1];
	const columnName = diff.path[3];
	const changeset: Changeset = {
		priority: MigrationOpPriority.ChangeColumnIdentityAdd,
		tableName: tableName,
		type: ChangeSetType.ChangeColumn,
		up:
			diff.value === "ALWAYS"
				? [
						executeKyselyDbStatement(
							`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" ADD GENERATED ALWAYS AS IDENTITY`,
						),
					]
				: [
						executeKyselyDbStatement(
							`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" ADD GENERATED BY DEFAULT AS IDENTITY`,
						),
					],
		down: [
			executeKyselyDbStatement(
				`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" DROP IDENTITY`,
			),
		],
	};
	return changeset;
}

function columnIdentityDropMigrationOperation(
	diff: IdentityDropDifference,
	schemaName: string,
) {
	const tableName = diff.path[1];
	const columnName = diff.path[3];
	const changeset: Changeset = {
		priority: MigrationOpPriority.ChangeColumnIdentityDrop,
		tableName: tableName,
		type: ChangeSetType.ChangeColumn,
		up: [
			executeKyselyDbStatement(
				`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" DROP IDENTITY`,
			),
		],
		down:
			diff.oldValue === "ALWAYS"
				? [
						executeKyselyDbStatement(
							`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" ADD GENERATED ALWAYS AS IDENTITY`,
						),
					]
				: [
						executeKyselyDbStatement(
							`ALTER TABLE "${schemaName}"."${tableName}" ALTER COLUMN "${columnName}" ADD GENERATED BY DEFAULT AS IDENTITY`,
						),
					],
	};
	return changeset;
}
