/* eslint-disable max-lines */
import { describe, expect, test } from "vitest";
import { changesetStats } from "~/changeset/changeset-stats.js";
import type { Changeset } from "~/changeset/types.js";

describe("changeset-summary", () => {
	test("Changeset summary", () => {
		const changeset = [
			{
				priority: 0,
				tableName: "none",
				schemaName: null,
				type: "createSchema",
				up: [],
				down: [],
			},
			{
				priority: 0,
				tableName: "none",
				schemaName: null,
				type: "createExtension",
				up: [],
				down: [
					["await sql`DROP EXTENSION IF EXISTS moddatetime;`", "execute(db);"],
				],
			},
			{
				priority: 0,
				tableName: "none",
				schemaName: null,
				type: "dropExtension",
				up: [],
				down: [],
			},
			{
				priority: 0,
				tableName: "none",
				schemaName: "public",
				type: "createEnum",
				up: [],
				down: [],
			},
			{
				priority: 0,
				tableName: "none",
				schemaName: "public",
				type: "changeEnum",
				up: [],
				down: [],
			},
			{
				priority: 810,
				tableName: "books",
				schemaName: "public",
				type: "dropIndex",
				up: [],
				down: [],
			},
			{
				priority: 810,
				tableName: "books",
				schemaName: "public",
				type: "dropIndex",
				up: [],
				down: [],
			},
			{
				priority: 810,
				tableName: "new_books",
				schemaName: "public",
				type: "dropIndex",
				up: [],
				down: [],
			},
			{
				priority: 810,
				tableName: "library_building",
				schemaName: "public",
				type: "dropForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 811,
				tableName: "library_building",
				schemaName: "public",
				type: "dropUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 811,
				tableName: "users",
				schemaName: "public",
				type: "dropUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 811,
				tableName: "users",
				schemaName: "public",
				type: "dropUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 812,
				tableName: "trigger_table",
				schemaName: "public",
				type: "dropCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 812,
				tableName: "books",
				schemaName: "public",
				type: "dropCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 812,
				tableName: "books",
				schemaName: "public",
				type: "dropCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 900,
				tableName: "books",
				schemaName: "public",
				type: "changeTable",
				up: [],
				down: [],
			},
			{
				priority: 900,
				tableName: "books",
				schemaName: "public",
				type: "changeTable",
				up: [],
				down: [],
			},
			{
				priority: 1001,
				tableName: "users",
				schemaName: "public",
				type: "dropTrigger",
				up: [],
				down: [],
			},
			{
				priority: 1001,
				tableName: "trigger_table",
				schemaName: "public",
				type: "dropTrigger",
				up: [],
				down: [],
			},
			{
				priority: 1001,
				tableName: "trigger_table",
				schemaName: "public",
				type: "dropTrigger",
				up: [],
				down: [],
			},
			{
				down: [],
				priority: 1004,
				tableName: "books",
				schemaName: "public",
				type: "dropPrimaryKey",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "books",
				schemaName: "public",
				type: "dropColumn",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "new_books",
				schemaName: "public",
				type: "dropColumn",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "new_books",
				schemaName: "public",
				type: "dropColumn",
				up: [],
			},
			{
				tableName: "users",
				schemaName: "public",
				type: "dropTable",
				priority: 1006,
				down: [],
				up: [],
			},
			{
				priority: 2001,
				tableName: "new_books",
				schemaName: "public",
				type: "createTable",
				up: [],
				down: [],
			},
			{
				priority: 2001,
				tableName: "trigger_table",
				schemaName: "public",
				type: "createTable",
				up: [],
				down: [],
			},
			{
				down: [],
				priority: 2001,
				tableName: "library_building",
				schemaName: "public",
				type: "createTable",
				up: [],
			},
			{
				priority: 2001,
				tableName: "users",
				schemaName: "public",
				type: "createTable",
				up: [],
				down: [],
			},
			{
				down: [],
				priority: 2001,
				tableName: "books",
				schemaName: "public",
				type: "createTable",
				up: [],
			},
			{
				down: [],
				priority: 2003,
				tableName: "books",
				schemaName: "public",
				type: "createColumn",
				up: [],
			},
			{
				down: [],
				priority: 2003,
				tableName: "new_books",
				schemaName: "public",
				type: "createColumn",
				up: [],
			},
			{
				down: [],
				priority: 2003,
				tableName: "new_books",
				schemaName: "public",
				type: "createColumn",
				up: [],
			},
			{
				down: [],
				priority: 3000,
				tableName: "new_books",
				schemaName: "public",
				type: "changeColumnName",
				up: [],
			},
			{
				down: [],
				priority: 3000,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumnName",
				up: [],
			},
			{
				down: [],
				priority: 3000,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumnName",
				up: [],
			},
			{
				down: [],
				priority: 3001,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3001,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3001,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3002,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3002,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3002,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3004,
				tableName: "books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3004,
				tableName: "new_books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3004,
				tableName: "new_books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3005,
				tableName: "new_books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3005,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3005,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3006,
				tableName: "library_building",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3006,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3006,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3007,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3007,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3007,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3008,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3008,
				tableName: "books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3008,
				tableName: "books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "users",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				down: [],
				priority: 3009,
				tableName: "books",
				schemaName: "public",
				type: "changeColumn",
				up: [],
			},
			{
				priority: 3011,
				tableName: "none",
				schemaName: "public",
				type: "dropEnum",
				up: [],
				down: [],
			},
			{
				priority: 3011,
				tableName: "none",
				schemaName: "public",
				type: "dropEnum",
				up: [],
				down: [],
			},
			{
				down: [],
				priority: 4001,
				tableName: "books",
				schemaName: "public",
				type: "createPrimaryKey",
				up: [],
			},
			{
				priority: 4001,
				tableName: "new_books",
				schemaName: "public",
				type: "createPrimaryKey",
				up: [],
				down: [],
			},
			{
				priority: 4001,
				tableName: "library_building",
				schemaName: "public",
				type: "createPrimaryKey",
				up: [],
				down: [],
			},
			{
				down: [],
				priority: 4003,
				tableName: "users",
				schemaName: "public",
				type: "createIndex",
				up: [],
			},
			{
				down: [],
				priority: 4003,
				tableName: "books",
				schemaName: "public",
				type: "createIndex",
				up: [],
			},
			{
				down: [],
				priority: 4003,
				tableName: "new_books",
				schemaName: "public",
				type: "createIndex",
				up: [],
			},
			{
				down: [],
				priority: 4003,
				tableName: "library_building",
				schemaName: "public",
				type: "createIndex",
				up: [],
			},
			{
				down: [],
				priority: 4003,
				tableName: "library_building",
				schemaName: "public",
				type: "createIndex",
				up: [],
			},
			{
				priority: 4004,
				tableName: "trigger_table",
				schemaName: "public",
				type: "createTrigger",
				up: [],
				down: [],
			},
			{
				priority: 4004,
				tableName: "books",
				schemaName: "public",
				type: "createTrigger",
				up: [],
				down: [],
			},
			{
				priority: 4004,
				tableName: "trigger_table",
				schemaName: "public",
				type: "createTrigger",
				up: [],
				down: [],
			},
			{
				priority: 4010,
				tableName: "books",
				schemaName: "public",
				type: "createUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 4010,
				tableName: "books",
				schemaName: "public",
				type: "createUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 4010,
				tableName: "new_books",
				schemaName: "public",
				type: "createUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 4011,
				tableName: "users",
				schemaName: "public",
				type: "createForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 4011,
				tableName: "new_books",
				schemaName: "public",
				type: "createForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 4011,
				tableName: "new_books",
				schemaName: "public",
				type: "createForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 4012,
				tableName: "new_books",
				schemaName: "public",
				type: "createCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 4012,
				tableName: "new_books",
				schemaName: "public",
				type: "createCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 4012,
				tableName: "trigger_table",
				schemaName: "public",
				type: "createCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeIndex",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeIndex",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "users",
				schemaName: "public",
				type: "changeIndex",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "trigger_table",
				schemaName: "public",
				type: "changeForeignKey",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "new_books",
				schemaName: "public",
				type: "changeUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "users",
				schemaName: "public",
				type: "changeUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "users",
				schemaName: "public",
				type: "changeUniqueConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "library_building",
				schemaName: "public",
				type: "changeCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "library_building",
				schemaName: "public",
				type: "changeCheckConstraint",
				up: [],
				down: [],
			},
			{
				priority: 5002,
				tableName: "users",
				schemaName: "public",
				type: "changeCheckConstraint",
				up: [],
				down: [],
			},
		] as Changeset[];

		const expected = {
			database: {
				extensions: { added: 1, dropped: 1 },
				schemaSummary: { added: 1, dropped: 0 },
			},
			databaseSchemas: {
				public: {
					tableSummary: {
						added: 5,
						dropped: 1,
						altered: 5,
					},
					tables: {
						books: {
							columns: { added: 1, dropped: 1, altered: 5 },
							primaryKeys: { added: 1, dropped: 1, altered: 0 },
							foreignKeys: { added: 0, dropped: 0, altered: 0 },
							checkConstraints: { added: 0, dropped: 2, altered: 0 },
							uniqueConstraints: { added: 2, dropped: 0, altered: 0 },
							indexes: { added: 1, dropped: 2, altered: 0 },
							triggers: { added: 1, dropped: 0, altered: 0 },
						},
						new_books: {
							columns: { added: 2, dropped: 2, altered: 4 },
							primaryKeys: { added: 1, dropped: 0, altered: 0 },
							foreignKeys: { added: 2, dropped: 0, altered: 0 },
							checkConstraints: { added: 2, dropped: 0, altered: 0 },
							uniqueConstraints: { added: 1, dropped: 0, altered: 1 },
							indexes: { added: 1, dropped: 1, altered: 0 },
							triggers: { added: 0, dropped: 0, altered: 0 },
						},
						library_building: {
							columns: { added: 0, dropped: 0, altered: 6 },
							primaryKeys: { added: 1, dropped: 0, altered: 0 },
							foreignKeys: { added: 0, dropped: 1, altered: 0 },
							checkConstraints: { added: 0, dropped: 0, altered: 2 },
							uniqueConstraints: { added: 0, dropped: 1, altered: 0 },
							indexes: { added: 2, dropped: 0, altered: 0 },
							triggers: { added: 0, dropped: 0, altered: 0 },
						},
						trigger_table: {
							columns: { added: 0, dropped: 0, altered: 6 },
							primaryKeys: { added: 0, dropped: 0, altered: 0 },
							foreignKeys: { added: 0, dropped: 0, altered: 2 },
							checkConstraints: { added: 1, dropped: 1, altered: 0 },
							uniqueConstraints: { added: 0, dropped: 0, altered: 0 },
							indexes: { added: 0, dropped: 0, altered: 2 },
							triggers: { added: 2, dropped: 2, altered: 0 },
						},
						users: {
							columns: { added: 0, dropped: 0, altered: 6 },
							primaryKeys: { added: 0, dropped: 0, altered: 0 },
							foreignKeys: { added: 1, dropped: 0, altered: 0 },
							checkConstraints: { added: 0, dropped: 0, altered: 1 },
							uniqueConstraints: { added: 0, dropped: 2, altered: 2 },
							indexes: { added: 1, dropped: 0, altered: 1 },
							triggers: { added: 0, dropped: 1, altered: 0 },
						},
					},
					enumTypes: {
						added: 1,
						dropped: 2,
						altered: 1,
					},
				},
			},
		};

		expect(changesetStats(changeset)).toEqual(expected);
	});
});
