export enum MigrationOpPriority {
	Database = 0,
	Table = 1,
	Column = 2,
	ChangeColumnDatatype = 3,
	ChangeColumnBase = 3.1,
	ChangeColumnIdentityAdd = 3.5,
	ChangeColumnIdentityDrop = 3.51,
	ChangeColumnDefaultAdd = 3.7,
	ChangeColumnDefaultDrop = 3.71,
	ChangeColumnDefaultChange = 3.72,
	ChangeColumnName = 3.8,
	IndexDrop = 3.79,
	Index = 4,
	ChangeIndex = 4.1,
	ConstraintDrop = 3.79,
	ConstraintCreate = 5.1,
	ConstraintChange = 5.2,
	TriggerDrop = 8,
	TriggerCreate = 8.1,
	TriggerUpdate = 8.2,
}
