export enum MigrationOpPriority {
	Database = 0,
	Table = 1,
	Column = 2,
	ChangeColumnDatatype = 3,
	ChangeColumnBase = 3.1,
	ChangeColumnIdentityAdd = 3.5,
	ChangeColumnIdentityDrop = 3.51,
	ChangeColumnDefaultAdd = 3.7,
	ChangeColumnDefaultDrop = 3.71,
	ChangeColumnDefaultChange = 3.72,
	Index = 4,
	ChangeIndex = 4.1,
	PrimaryKeyDrop = 5,
	PrimaryKeyReplace = 5.1,
	PrimaryKeyCreate = 5.11,
	PrimaryKeyUpdate = 5.12,
	UniqueConstraintDrop = 6,
	UniqueConstraintCreate = 6.11,
	UniqueConstraintChange = 6.12,
	ForeignKeyConstraintDrop = 7,
	ForeignKeyConstraintCreate = 7.11,
	ForeignKeyConstraintChange = 7.12,
	TriggerDrop = 8,
	TriggerCreate = 8.1,
	TriggerUpdate = 8.2,
}
