import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    { type: "category",
      label: "Schema definition",
      items: [
        { type: 'autogenerated', dirName: 'schema-definition'}
      ]
    },
    'generated-types',
    'validations-with-zod',
    { type: "category",
      label: "Workflows",
      items: [
        { type: 'autogenerated', dirName: 'workflows'}
      ]
    },
    'custom-migrations',
    'seeding-database',
    { type: "category",
      label: "Configuration",
      items: [
        { type: 'autogenerated', dirName: 'configuration'}
      ]
    },
    { type: "category",
      label: "CLI commands",
      items: [
        { type: 'autogenerated', dirName: 'cli'}
      ]
    },
  ],
  typedocSidebar: [
    {
      type: 'category',
      label: 'monolayer',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: require("./docs/api/typedoc-sidebar.cjs"),
    },
  ],
};

export default sidebars;
